### ISSUE TITLE
Needs a "beginner's mind" review

### ISSUE THREAD

**Issue by finnhodgkin** [foundersandcoders/morning-challenge-traffic-lights#2]
I think I'm currently the only person to complete this. 

It would be great to get some more opinions on the difficulty level / code clarity.

**Comment by ZooeyMiller** [comment]
I worked through up to step 4 but didn't complete step 4 (just because it was more of the same). I think it's fine in terms of difficulty, the hint.md will level the playing field with people who are struggling. Though I'd probably suggest they try not to use it for 1st 30 mins or something so they can give it a proper go on their own.

**Comment by nelsonic** [comment]
+ How do I *run* the project? (_e.g: Live Server?_)

**Comment by nelsonic** [comment]
```
git clone https://github.com/finnhodgkin/morning-challenge-traffic-lights.git
```
should be:
```
git clone https://github.com/foundersandcoders/morning-challenge-traffic-lights.git
```

**Comment by nelsonic** [comment]
@finnhodgkin got it working with the help of `hint.md` 👍 
I think for _complete beginners_ there's the _potential_ for "_confusion_". 😕 
But it's an _opportunity_ to get them to ask clarifying questions... 😉

**Comment by finnhodgkin** [comment]
Thanks @nelsonic! Super helpful I'll definitely add live server. 

I'm happy with a bit of confusion in morning challenges - I'll just have to keep on my toes to make sure there aren't any _uncomfortably_ confused people.
